[project]
name = "text-to-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jassi789012", email = "jassi789012singh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-google-genai>=4.4.0",
    "langchain-groq>=1.1.3",
    "langchain-ollama>=1.1.0",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "pandas>=3.0.5",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
text-to-sql = "text_to_sql:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
